---
title: "EDS Jobs Summary for Kickoff"
author: "Jamie Montgomery"
date: "6/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Attach packages: 
library(googledrive)
library(stringr)
library(readr)
library(tidyverse)
library(ggplot2)
library(ggwordcloud)
library(patchwork)
```


```{r, eval = FALSE}
# List all google docs in the jobs folder
jobs <- drive_ls("https://drive.google.com/drive/u/0/folders/1MMeiTL6C_AlJVkM6No8OQKzDzYFkY5GW")

for (i in 31:nrow(jobs)){
  print(i)
  
  job <- jobs[i,]$name

  if (str_detect(job, ".pdf")) next 
  
drive_download(job, type = "text", path = paste0("../raw-data/", job, ".txt"), overwrite = TRUE)
}
```

Create dictionary of words to look for:

```{r}

words <- c(" r ", " r,", "rstudio", "git ", " git, ", "github", "python", "remote sensing", "remotely sensed",  "spatial", "javascript", "sql", "arcgis", " gis ", " gis, ", "aws", "cloud", "machine learning", " sas ", " sas, ", "qgis", "tableau", "excel", "google sheets", "tensorflow", "pytorch", "matlab", "google earth engine", "stata", " api ", " api,", "shiny", "jupyter", "time series", "kepler", "docker", "css", "azure", "kubernetes", "dashboard", "metadata", "data visualization" ,"data management", "rmarkdown", "html", "bash")

```

Test

```{r}

# Create a placeholder data frame
df <- data.frame(title = "NA", skill = "NA")

# Read in job description file names from raw-data
job_descriptions <- list.files(here::here("raw-data"), full.names = TRUE)

#read in job
for (i in 1:length(job_descriptions)) {
  
  a <- read_lines(job_descriptions[i]) %>%
  tolower()
  
  job <- substr(job_descriptions[i],13,nchar(job_descriptions[i])-4)
  print(job)
  
#run through all words 
for (j in 1:length(words)){

  word <- words[j]
  t <- str_detect(a, word)
  
  if(TRUE %in% t){
 df <- df %>% add_row(title = job, skill = word) 
  }
}  
}
```

Separate title into job and employer

```{r}
df2 <- df %>%
  separate(title, into = c("position", "employer"), sep = " - ") %>%
  filter(!is.na(employer))
```


```{r, fig.height = 5, fig.width = 4}

num_skills <- df2 %>%
  mutate(skill = case_when(
    skill %in% c(" r ", " r,", "rstudio") ~ "R",
    skill %in% c("git ", " git, ", "github") ~ "git/GitHub",
    skill %in% c(" gis ", " gis, ") ~ "GIS",
    skill %in% c(" sas ", " sas, ") ~ "SAS",
    skill == "python" ~ "Python",
    skill == "excel" ~ "Excel",
    skill %in% c("remote sensing", "remotely sensed") ~ "Remote Sensing",
    skill == "matlab" ~ "MATLAB",
    skill == "docker" ~ "Docker",
    skill == "html" ~ "HTML",
    skill == "arcgis" ~ "ArcGIS",
    skill == "qgis" ~ "QGIS",
    skill %in% c(" api ", " api,") ~ "API",
    skill == "shiny" ~ "Shiny",
    skill == "sql" ~ "SQL",
    skill == "javascript" ~ "JavaScript",
    skill == "css" ~ "CSS",
    skill == "aws" ~ "AWS",
    skill == "pytorch" ~ "PyTorch",
    skill == "google earth engine" ~ "Google Earth Engine",
    skill == "tableau" ~ "Tableau",
    TRUE ~ as.character(skill))) %>%
  distinct() %>%
  group_by(skill) %>%
  summarize(count = n()) %>%
  mutate(prop = round(count/length(job_descriptions),2))

software <- num_skills %>%
  filter(skill %in% c("R", "git/GitHub", "Python", "JavaScript", "MATLAB", "SQL", "ArcGIS", "AWS","SAS", "QGIS", "Tableau", "Excel", "google sheets", "tensorflow", "PyTorch", "Google Earth Engine", "stata", "Shiny", "jupyter", "kepler", "Docker", "CSS", "azure", "kubernetes", "rmarkdown", "HTML", "bash"))

# Narrow to top 10 for paper
software_top10 <- software %>% 
  top_n(wt = prop, n = 10)

tools_software <- ggplot(software_top10, aes(reorder(skill,count), y = prop)) +
  geom_col() +
  theme_bw() +
  coord_flip() +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.7),
                     expand = c(0,0),
                     breaks = c(0, 0.2, 0.4, 0.6)) +
  labs(y = "\nProportion (%) of postings this \ntool or software appears in", 
       x = "",
       title = "Tools / software") +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank())


ggsave(tools_software, filename = "software.png",dpi = 600)


```

```{r}
non_soft <- num_skills %>%
  filter(!skill %in% c("R", "git/GitHub", "Python", "JavaScript", "MATLAB", "SQL", "ArcGIS", "AWS","SAS", "QGIS", "Tableau", "Excel", "google sheets", "tensorflow", "PyTorch", "matlab", "Google Earth Engine", "stata", "Shiny", "jupyter", "kepler", "Docker", "CSS", "azure", "kubernetes", "rmarkdown", "HTML", "bash")) %>% 
  mutate(skill = str_to_title(skill)) %>% 
  mutate(skill = case_when(
    skill == "Api" ~ "API",
    skill == "Gis" ~ "GIS",
    TRUE ~ skill
  )) 

non_soft_top10 <- non_soft %>% 
  top_n(n = 10, wt = prop)

skills_knowledge <- ggplot(non_soft_top10, aes(reorder(skill,prop), y = prop)) +
  geom_col() +
  theme_bw() +
  coord_flip() +
  labs(y = "\nProportion (%) of postings this \nskill or knowledge appears in", 
       x = "",
       title = "Skills / knowledge") +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.5),
                     expand = c(0,0),
                     breaks = c(0, 0.2, 0.4)) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.border = element_blank())

ggsave(skills_knowledge, filename = "general_knowledge.png",dpi = 600)
```

Combining figures (for tools / software and skills / knowledge graphs)
```{r}
top10_combined <- tools_software | skills_knowledge

ggsave(top10_combined, width = 8, height = 4, dpi = 600, filename = "top10_combined.png")
```


```{r, fig.height=5, fig.width=6}
num_jobs <- df2 %>% 
  select(position, employer) %>%
  distinct() %>%
  mutate(position = str_replace_all(position, "_", "/")) %>%
  group_by(position) %>%
  summarize(count = n())

ggplot(num_jobs, aes(label = position, size = count, color = position)) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 6) +
  theme_minimal()


ggsave(filename = "../job_titles.png",dpi = 600)
```

Employers

```{r, fig.height=5, fig.width=7}
num_employers <- df2 %>% 
  select(employer) %>%
  distinct() %>%
  group_by(employer) %>%
  summarize(count = n())


ggplot(num_employers, aes(label = employer, size = count, color = employer)) +
  geom_text_wordcloud() +
  scale_size_area(max_size = 4.5) +
  theme_minimal() 


ggsave(filename = "../employers.png",dpi = 600)
```


